language: python
python:
  - "2.7"

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"

# command to install dependencies
install:
  - "pip install -r requirements.txt"
  - "python manage.py syncdb"
# command to run tests
script:
  - "coverage run --source='.' -p manage.py test courses accounts"
  - "coverage run --source='.' -p manage.py test functional_tests"

after_success:
  - coverage combine
  - coveralls